[build]
  command = "npm run build"
  publish = ".svelte-kit/output/client"

# Прокидываем все пути в SSR-функцию SvelteKit
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/sveltekit-render"
  status = 200
