[build]
command = "npm run build"
publish = ".svelte-kit/output/client"

[build.environment]
NODE_VERSION = "20"

# ВАЖНО: отправляем весь трафик в функцию рендера SvelteKit
[[redirects]]
from = "/*"
to = "/.netlify/functions/sveltekit-render"
status = 200